# Generated by Django 4.0.4 on 2022-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(max_length=100)),
                ('ad_status', models.CharField(max_length=100)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_weight', models.CharField(max_length=100)),
                ('or_rate', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_date', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(default=0, max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_image', models.ImageField(upload_to='app/static/media/products/')),
                ('ap_type', models.CharField(max_length=100)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_weight', models.CharField(max_length=100)),
                ('ap_rate', models.CharField(max_length=100)),
                ('ap_description', models.CharField(max_length=100)),
                ('ap_status', models.CharField(default=0, max_length=100)),
                ('ap_created_by', models.CharField(max_length=100)),
                ('ap_created_name', models.CharField(max_length=100)),
            ],
        ),
    ]
