# Generated by Django 4.0.4 on 2022-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('b_property_name', models.CharField(max_length=100)),
                ('b_purchaser_name', models.CharField(max_length=100)),
                ('b_place', models.CharField(max_length=100)),
                ('b_amount', models.CharField(max_length=100)),
                ('b_date', models.CharField(max_length=100)),
                ('b_status', models.CharField(max_length=100)),
                ('b_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_status', models.CharField(max_length=100)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pr_seller_name', models.CharField(max_length=100)),
                ('pr_property_type', models.CharField(max_length=100)),
                ('pr_place', models.CharField(max_length=100)),
                ('pr_date', models.CharField(max_length=100)),
                ('pr_mobile_no', models.CharField(max_length=100)),
                ('pr_status', models.CharField(max_length=100)),
                ('pr_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_mobile', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('s_password', models.CharField(max_length=100)),
                ('s_status', models.CharField(max_length=100)),
                ('s_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
