# Generated by Django 4.0.4 on 2022-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_category_properties_seller_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSeller',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_mobile', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('s_password', models.CharField(max_length=100)),
                ('s_role', models.CharField(max_length=100)),
                ('s_status', models.CharField(max_length=100)),
                ('s_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Booking',
            new_name='AdminBooking',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='AdminCategory',
        ),
        migrations.RenameModel(
            old_name='Properties',
            new_name='AdminProperties',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
