# Generated by Django 4.0.4 on 2022-06-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminseller_rename_booking_adminbooking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminCategory',
            new_name='SellerCategories',
        ),
    ]
