# Generated by Django 4.0.4 on 2022-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_admincategory_sellercategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProperties',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pr_seller_name', models.CharField(max_length=100)),
                ('pr_property_type', models.CharField(max_length=100)),
                ('pr_place', models.CharField(max_length=100)),
                ('pr_date', models.CharField(max_length=100)),
                ('pr_mobile_no', models.CharField(max_length=100)),
                ('pr_status', models.CharField(max_length=100)),
                ('pr_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminProperties',
        ),
    ]
