# Generated by Django 4.0.4 on 2022-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sellerproperties_delete_adminproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('h_name', models.CharField(max_length=100)),
                ('h_mobile', models.CharField(max_length=100)),
                ('h_email', models.CharField(max_length=100)),
                ('h_password', models.CharField(max_length=100)),
                ('h_hall', models.CharField(max_length=100)),
                ('h_status', models.CharField(max_length=100)),
                ('h_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='AdminBooking',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='SellerCategories',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='AdminSeller',
        ),
        migrations.DeleteModel(
            name='SellerProperties',
        ),
    ]
