# Generated by Django 4.0.4 on 2022-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hall_rename_adminbooking_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sr_name', models.CharField(max_length=100)),
                ('sr_status', models.CharField(max_length=100)),
                ('sr_created_by', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
