# Generated by Django 4.0.4 on 2022-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sr_created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='sr_status',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
