# Generated by Django 4.0.4 on 2022-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fc_name', models.CharField(max_length=100)),
                ('fc_status', models.IntegerField(default=0, max_length=100)),
                ('fc_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
