# Generated by Django 4.0.4 on 2022-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sp_name', models.CharField(max_length=100)),
                ('sp_mobile', models.CharField(max_length=100)),
                ('sp_email', models.CharField(max_length=100)),
                ('sp_password', models.CharField(max_length=100)),
                ('sp_status', models.CharField(max_length=100)),
                ('sp_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
