# Generated by Django 4.0.4 on 2022-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('em_name', models.CharField(max_length=100)),
                ('em_mobile', models.CharField(max_length=100)),
                ('em_email', models.CharField(max_length=100)),
                ('em_password', models.CharField(max_length=100)),
                ('em_designation', models.CharField(max_length=100)),
                ('em_status', models.CharField(max_length=100)),
                ('em_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
