# Generated by Django 4.0.4 on 2022-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='h_image',
            field=models.FileField(default='', upload_to='app/static/media/image'),
        ),
    ]
