# Generated by Django 4.0.4 on 2022-06-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hall_h_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bk_hall_name', models.CharField(max_length=100)),
                ('bk_hall_email', models.CharField(max_length=100)),
                ('bk_user_name', models.CharField(max_length=100)),
                ('bk_user_email', models.CharField(max_length=100)),
                ('bk_user_address', models.CharField(max_length=100)),
                ('bk_user_phone', models.CharField(max_length=100)),
                ('bk_date', models.CharField(max_length=100)),
                ('bk_guest_count', models.CharField(max_length=100)),
                ('bk_hall_cost', models.CharField(max_length=100)),
                ('bk_status', models.CharField(max_length=100)),
                ('bk_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='facility',
            name='fc_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='pk_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='sr_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vn_status',
            field=models.IntegerField(default=0),
        ),
    ]
