# Generated by Django 4.0.4 on 2022-06-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_book_alter_facility_fc_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_status', models.IntegerField(default=0)),
                ('us_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
