# Generated by Django 4.0.4 on 2022-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_status',
            field=models.IntegerField(default=0),
        ),
    ]
