# Generated by Django 4.0.4 on 2022-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_book_bk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_booking_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
