# Generated by Django 4.0.4 on 2022-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_book_bk_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('py_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('py_hall_name', models.CharField(max_length=100)),
                ('py_hall_amount', models.CharField(max_length=100)),
                ('py_user_name', models.CharField(max_length=100)),
                ('py_user_email', models.CharField(max_length=100)),
                ('py_user_address', models.CharField(max_length=100)),
                ('py_user_phone', models.CharField(max_length=100)),
                ('py_status', models.IntegerField(default=0)),
                ('py_created_at', models.DateTimeField(auto_now=True)),
                ('py_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
