# Generated by Django 4.0.5 on 2022-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_adminmaster_ad_status_alter_booking_b_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
