# Generated by Django 4.0.5 on 2022-07-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pk_duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
