# Generated by Django 4.0.5 on 2022-07-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_package_pk_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_fees',
            field=models.CharField(default='', max_length=100),
        ),
    ]
