# Generated by Django 4.0.5 on 2022-07-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_book_bk_duration_book_bk_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bk_guest_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bk_hall_cost',
        ),
    ]
