# Generated by Django 4.0.5 on 2022-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_register_us_mobile_register_us_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ct_video',
            field=models.TextField(default=''),
        ),
    ]
