# Generated by Django 4.0.5 on 2022-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_book_bk_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ct_request',
            field=models.CharField(default='', max_length=100),
        ),
    ]
