# Generated by Django 4.0.5 on 2022-08-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_category_ct_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ct_request',
        ),
        migrations.AddField(
            model_name='hall',
            name='h_document',
            field=models.FileField(default='', upload_to='app/static/media/document'),
        ),
    ]
