# Generated by Django 4.0.5 on 2022-08-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_video', models.TextField(default='')),
                ('ct_status', models.CharField(default=0, max_length=100)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
