# Generated by Django 4.0.5 on 2022-08-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_subject_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='TutorialDetails',
        ),
    ]
