# Generated by Django 4.0.5 on 2022-08-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_services_tutorialdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hall',
            new_name='Tutor',
        ),
    ]
