# Generated by Django 4.0.5 on 2022-08-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_hall_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
