# Generated by Django 4.2.3 on 2023-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_delete_employee_delete_facility_delete_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='h_hall',
        ),
        migrations.AddField(
            model_name='tutor',
            name='h_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
