# Generated by Django 4.2.3 on 2023-08-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_tutor_h_hall_tutor_h_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='us_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
