# Generated by Django 4.2.3 on 2023-08-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_register_us_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='h_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='h_location',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
