# Generated by Django 4.2.3 on 2024-04-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_tutor_h_address_alter_tutor_h_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('at_student_id', models.CharField(default='', max_length=100)),
                ('at_class_id', models.CharField(max_length=100)),
                ('at_status', models.IntegerField(default=0)),
                ('at_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cl_day_id', models.CharField(max_length=100)),
                ('cl_time', models.CharField(default='', max_length=100)),
                ('cl_faculty_id', models.CharField(default='', max_length=100)),
                ('cl_subject_id', models.CharField(default='', max_length=100)),
                ('cl_status', models.IntegerField(default=0)),
                ('cl_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day_name', models.CharField(default='', max_length=100)),
                ('day_status', models.IntegerField(default=0)),
                ('day_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fc_name', models.CharField(max_length=100)),
                ('fc_mobile', models.CharField(max_length=100)),
                ('fc_email', models.CharField(max_length=100)),
                ('fc_role', models.CharField(max_length=100)),
                ('fc_status', models.IntegerField(default=0)),
                ('fc_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorialDetails',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='us_password',
            new_name='us_parent_email',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='ct_id',
            new_name='su_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ct_created_by',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ct_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ct_status',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ct_video',
        ),
        migrations.AddField(
            model_name='register',
            name='us_usn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='su_created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='su_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='su_status',
            field=models.IntegerField(default=0),
        ),
    ]
