# Generated by Django 4.2.3 on 2024-04-17 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_register_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='at_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
